service: lawnow-webapp
image: greenstarkmucs/lawnow-webapp

servers:
  web:
    hosts:
      - 10.0.0.6
    options:
      add-host: host.docker.internal:host-gateway
      network: deploy
ssh:
  user: greenstar1151
  port: 22

registry:
  username: greenstarkmucs
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "lawnow-webapp_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64
