title: "LawNow"
description: "LawNow 프로젝트 문서화"
plugins:
  - jekyll-remote-theme    
  - jekyll-redirect-from
remote_theme: just-the-docs/just-the-docs
# GitHub Pages URL 설정
url: "https://kookmin-sw.github.io"
baseurl: "/capstone-2025-01"

search_enabled: false
aux_links:
  Github: https://github.com/kookmin-sw/capstone-2025-01

# 사이드바 설정
aux_links_new_tab: true
heading_anchors: true

# 로고 설정
logo: "/assets/images/brand_logo.svg"

# footer
footer_content: "© 2025 LawNow. 국민대학교 캡스톤 2025-01팀"
